# Configuration for EPEver Serial Device
############################################################

# Serial config for the Tracer Device...
serialPort: /dev/ttyXRUSB0
baudRate: 115200
flowControl: none
parity: none
char: 8
stopBits: 1

# Home Assistant MQTT server:
mqttServer: 192.168.1.4
mqttPort: 1883
mqttTopic: homeassistant
mqttDevicename: tracer_1


# How often poll for data (in seconds)
pollingInterval: 10
verboseDebugging: false # set to true to debug sensor values in log.