apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-logger
spec:
  selector:
    matchLabels:
      app: solar-logger
  replicas: 1
  template:
    metadata:
      labels:
        app: solar-logger
    spec:
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          secretName: solar-logger-config
      containers:
        - image: "cjj25/solar-epever-homeassistant-esplink:latest"
          env:
            - name: ESP_LINK_TCP_ADDR
              value: 192.168.253.250:23
          imagePullPolicy: IfNotPresent
          name: solar-logger
          volumeMounts:
          - name: config
            mountPath: "/opt/epever/config/config.yml"
            readOnly: true

---
apiVersion: v1
kind: Secret
metadata:
  name: solar-logger-config
type: Opaque
stringData:
  config.yaml: |
      # Configuration for EPEver Serial Device
      ############################################################

      # Serial config for the Tracer Device...
      serialPort: /dev/ttyXRUSB0
      baudRate: 115200
      flowControl: none
      parity: none
      char: 8
      stopBits: 1

      # Home Assistant MQTT server:
      mqttServer: 192.168.1.4
      mqttPort: 1883
      mqttTopic: homeassistant
      mqttDevicename: tracer_1
  
      # How often poll for data (in seconds)
      pollingInterval: 10
      verboseDebugging: false # set to true to debug sensor values in log.
    
    